### ISSUE TITLE
Stopped working in nuxt 3.0.0-rc.14   

### ISSUE THREAD

**Issue by andorfermichael** [nuxt-community/dayjs-module#451] opened 2022-11-16 07:36 UTC
The plugin worked well until nuxt 3.0.0-rc.13 but starting from nuxt 3.0.0-rc.14 it fails as follows:

```
 Cannot read properties of undefined (reading 'dayjs')                                                                                                                                                                                 08:31:00

  at dayjsModule (node_modules/@nuxtjs/dayjs/lib/module.js:5:37)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1827:7)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1859:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:493:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:30:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by danielroe** [comment] 2022-11-16 11:56
This should be resolved in the next Nuxt release and is not an issue with this module.

If you need a workaround before the next version of nuxt is released, you can add the following to your nuxt config:

```js
runtimeConfig: { public: {} },
```

**Comment by andorfermichael** [comment] 2022-11-17 05:58
@danielroe still not working in the next version of nuxt which is [v3.0.0](https://github.com/nuxt/framework/releases/tag/v3.0.0)

I also cannot apply the workaround because I already have values in runtimeConfig public.

**Comment by yeonjulee1005** [comment] 2022-12-30 02:46
I also wait for official module support! 🙏🏻

**Comment by timothymarois** [comment] 2023-02-08 17:46
Also seeing that this wont work in nuxt3

**Comment by Dinuz** [comment] 2023-02-22 01:16
Yeah still same error and workaround doesn't really work with nuxt 3.2.2 same exact error of @andorfermichael . @danielroe we got up in version but nothing still solved, what do you think the issue is?

**Comment by joseehilton147** [comment] 2023-03-03 19:50
any news?

**Comment by davvvvsss** [comment] 2023-05-27 14:34
Any?

**Comment by harlan-zw** [comment] 2023-09-11 11:23
Going to track Nuxt 3 support in this issue https://github.com/nuxt-community/dayjs-module/issues/451

**Closed by harlan-zw** 2023-09-11 11:23 UTC

**Comment by amakavanessa** [comment] 2023-11-09 09:38
Ran into the same error a while ago and solved it by using [Day.js](https://nuxt.com/modules/dayjs). I was able to access Day.js like this:

const dayjs = useDayjs();
const today = dayjs();
